### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Retourne la composition de deux fonctions.


  À partir de deux fonctions $f $ et $g $, retourne une nouvelle fonction représentant $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Deuxième fonction à appliquer.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Première fonction à appliquer.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Une nouvelle fonction $h $ de telle sorte que toutes les entrées $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Type d’entrée de la première fonction à appliquer.
- uid: "'U"
  summary: Type de sortie de la première fonction à appliquer et type d’entrée de la deuxième fonction à appliquer.
- uid: "'V"
  summary: Type de sortie de la deuxième fonction à appliquer.
metadata:
  ms.openlocfilehash: 77037411aace0f69850b62322f3e63d6a34358ed
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82675814"
